run-name: Linting of javascript files
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        cd theia-extension/ide-ai-assistant
        yarn
    - name: Run ESLint
      run: |
        cd theia-extension/ide-ai-assistant
        yarn eslint .
