run-name: Building, linting and testing
on: push

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn
    - name: Build Browser App
      run: |
        yarn build:browser
    - name: Run theia-extension tests
      run: |
        yarn test:theia
    - name: Run eslint
      run: |
        cd extensions/ai-assistant-theia
        yarn
        yarn eslint .
    - name: Run vsc-extension tests
      run: |
        cd extensions/ai-assistant-vsc
        yarn
        xvfb-run -a yarn test
        
