run-name: Building, linting and testing
on: push

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn
    - name: Run eslint on entire project
      run: | 
        yarn lint
    - name: Run tests
      run: |
        yarn test
        
